import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  learnSidebar: [
    {
      type: 'category',
      label: 'AWS',
      items: [
        {
          type: 'category',
          label: 'CLF-C02云从业者',
          link: {
            type: 'generated-index',
            slug: '/aws/clf-c02',
            title: 'AWS-CLF-C02学习中心',
            description: 'AWS-CLF-C02知识文档、架构场景、题目解析与考前复习。',
          },
          items: [{type: 'autogenerated', dirName: 'aws/clf-c02'}],
        },
      ],
    },
  ],
};

export default sidebars;
